### ISSUE TITLE
httpCode SerializeException(message: "statusCode expected type: \'Int.Type but is \'Optional<Any>")

### ISSUE THREAD

**Issue by ozcanakkoca3401** [enciyo/FlipMockiOS#1]
func mapMock() throws -> Mock  {
        return Mock(
            endpoint: try parseMap("endpoint", transform: {item -> String in item }),
            dummyJsonData: try parseMap("dummyJsonData", transform: {item -> String in item.description }),
            uniqueId: try parseMap("uniqueId", transform: {item -> String in item }),
            queryParams: try parseMap("queryParams", transform: {item -> String in item }),
            httpCode: httpCodeMap(),
            requestType: MockRequestMethods.safeValueOf(value: (try parseMap("httpMethod", transform: {item -> String in item }))),
            isMockEnable: try parseMap("isMockEnable", transform: {item -> Bool in item})
        )
    }

    func httpCodeMap() -> Int {
        if let code = self["statusCode"] as? String {
            return Int(code) ?? 200
        } else if let code = self["statusCode"] as? Int {
            return code
        } else {
            return 200
        }
    }

**Comment by enciyo** [comment]
Fixed, v1.0.3
